"""init migration

Revision ID: ced5bd8b016d
Revises: 
Create Date: 2024-01-22 19:38:45.659205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ced5bd8b016d"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "applications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("version", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("created_date", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_applications_id"), "applications", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_applications_name"), "applications", ["name"], unique=True
    )
    op.create_table(
        "arp_table_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ip_address", sa.String(), nullable=True),
        sa.Column("mac_address", sa.String(), nullable=True),
        sa.Column("created_date", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_arp_table_items_id"), "arp_table_items", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_arp_table_items_mac_address"),
        "arp_table_items",
        ["mac_address"],
        unique=True,
    )
    op.create_table(
        "connections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_date", sa.DateTime(), nullable=True),
        sa.Column("protocol", sa.String(), nullable=True),
        sa.Column("src_ip_address", sa.String(), nullable=True),
        sa.Column("src_port", sa.Integer(), nullable=True),
        sa.Column("dst_ip_address", sa.String(), nullable=True),
        sa.Column("dst_port", sa.Integer(), nullable=True),
        sa.Column("state", sa.String(), nullable=True),
        sa.Column("service_name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_connections_id"), "connections", ["id"], unique=False
    )
    op.create_table(
        "current_applications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("version", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("created_date", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_current_applications_id"),
        "current_applications",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_current_applications_name"),
        "current_applications",
        ["name"],
        unique=True,
    )
    op.create_table(
        "current_arp_table_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ip_address", sa.String(), nullable=True),
        sa.Column("mac_address", sa.String(), nullable=True),
        sa.Column("created_date", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_current_arp_table_items_id"),
        "current_arp_table_items",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_current_arp_table_items_mac_address"),
        "current_arp_table_items",
        ["mac_address"],
        unique=True,
    )
    op.create_table(
        "current_connections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_date", sa.DateTime(), nullable=True),
        sa.Column("protocol", sa.String(), nullable=True),
        sa.Column("src_ip_address", sa.String(), nullable=True),
        sa.Column("src_port", sa.Integer(), nullable=True),
        sa.Column("dst_ip_address", sa.String(), nullable=True),
        sa.Column("dst_port", sa.Integer(), nullable=True),
        sa.Column("state", sa.String(), nullable=True),
        sa.Column("service_name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_current_connections_id"),
        "current_connections",
        ["id"],
        unique=False,
    )
    op.create_table(
        "current_hosts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ip_address", sa.String(), nullable=True),
        sa.Column("mac_address", sa.String(), nullable=True),
        sa.Column("created_date", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_current_hosts_id"), "current_hosts", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_current_hosts_ip_address"),
        "current_hosts",
        ["ip_address"],
        unique=True,
    )
    op.create_index(
        op.f("ix_current_hosts_mac_address"),
        "current_hosts",
        ["mac_address"],
        unique=True,
    )
    op.create_table(
        "current_network_interfaces",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("ip_address", sa.String(), nullable=True),
        sa.Column("created_date", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_current_network_interfaces_id"),
        "current_network_interfaces",
        ["id"],
        unique=False,
    )
    op.create_table(
        "current_structural_functional_characteristics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("version", sa.String(), nullable=True),
        sa.Column("created_date", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_current_structural_functional_characteristics_id"),
        "current_structural_functional_characteristics",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_current_structural_functional_characteristics_name"),
        "current_structural_functional_characteristics",
        ["name"],
        unique=True,
    )
    op.create_table(
        "current_system_services",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("created_date", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_current_system_services_id"),
        "current_system_services",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_current_system_services_name"),
        "current_system_services",
        ["name"],
        unique=True,
    )
    op.create_table(
        "hosts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ip_address", sa.String(), nullable=True),
        sa.Column("mac_address", sa.String(), nullable=True),
        sa.Column("created_date", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_hosts_id"), "hosts", ["id"], unique=False)
    op.create_index(
        op.f("ix_hosts_ip_address"), "hosts", ["ip_address"], unique=True
    )
    op.create_index(
        op.f("ix_hosts_mac_address"), "hosts", ["mac_address"], unique=True
    )
    op.create_table(
        "monitor_resources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_date", sa.DateTime(), nullable=True),
        sa.Column("ram_usage", sa.Float(), nullable=True),
        sa.Column("swap_usage", sa.Float(), nullable=True),
        sa.Column("disk_usage", sa.Float(), nullable=True),
        sa.Column("uptime", sa.String(), nullable=True),
        sa.Column("cpu_load", sa.Float(), nullable=True),
        sa.Column("cpu_temperature", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_monitor_resources_id"),
        "monitor_resources",
        ["id"],
        unique=False,
    )
    op.create_table(
        "network_interfaces",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("ip_address", sa.String(), nullable=True),
        sa.Column("created_date", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_network_interfaces_id"),
        "network_interfaces",
        ["id"],
        unique=False,
    )
    op.create_table(
        "structural_functional_characteristics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("version", sa.String(), nullable=True),
        sa.Column("created_date", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_structural_functional_characteristics_id"),
        "structural_functional_characteristics",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_structural_functional_characteristics_name"),
        "structural_functional_characteristics",
        ["name"],
        unique=True,
    )
    op.create_table(
        "system_services",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("created_date", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_system_services_id"), "system_services", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_system_services_name"),
        "system_services",
        ["name"],
        unique=True,
    )
    op.create_table(
        "current_ports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("host_id", sa.String(), nullable=True),
        sa.Column("port", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("service", sa.String(), nullable=True),
        sa.Column("protocol", sa.String(), nullable=True),
        sa.Column("created_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["host_id"],
            ["current_hosts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_current_ports_host_id"),
        "current_ports",
        ["host_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_current_ports_id"), "current_ports", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_current_ports_port"), "current_ports", ["port"], unique=False
    )
    op.create_table(
        "ports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("host_id", sa.String(), nullable=True),
        sa.Column("port", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("service", sa.String(), nullable=True),
        sa.Column("protocol", sa.String(), nullable=True),
        sa.Column("created_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["host_id"],
            ["hosts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ports_host_id"), "ports", ["host_id"], unique=False
    )
    op.create_index(op.f("ix_ports_id"), "ports", ["id"], unique=False)
    op.create_index(op.f("ix_ports_port"), "ports", ["port"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ports_port"), table_name="ports")
    op.drop_index(op.f("ix_ports_id"), table_name="ports")
    op.drop_index(op.f("ix_ports_host_id"), table_name="ports")
    op.drop_table("ports")
    op.drop_index(op.f("ix_current_ports_port"), table_name="current_ports")
    op.drop_index(op.f("ix_current_ports_id"), table_name="current_ports")
    op.drop_index(op.f("ix_current_ports_host_id"), table_name="current_ports")
    op.drop_table("current_ports")
    op.drop_index(
        op.f("ix_system_services_name"), table_name="system_services"
    )
    op.drop_index(op.f("ix_system_services_id"), table_name="system_services")
    op.drop_table("system_services")
    op.drop_index(
        op.f("ix_structural_functional_characteristics_name"),
        table_name="structural_functional_characteristics",
    )
    op.drop_index(
        op.f("ix_structural_functional_characteristics_id"),
        table_name="structural_functional_characteristics",
    )
    op.drop_table("structural_functional_characteristics")
    op.drop_index(
        op.f("ix_network_interfaces_id"), table_name="network_interfaces"
    )
    op.drop_table("network_interfaces")
    op.drop_index(
        op.f("ix_monitor_resources_id"), table_name="monitor_resources"
    )
    op.drop_table("monitor_resources")
    op.drop_index(op.f("ix_hosts_mac_address"), table_name="hosts")
    op.drop_index(op.f("ix_hosts_ip_address"), table_name="hosts")
    op.drop_index(op.f("ix_hosts_id"), table_name="hosts")
    op.drop_table("hosts")
    op.drop_index(
        op.f("ix_current_system_services_name"),
        table_name="current_system_services",
    )
    op.drop_index(
        op.f("ix_current_system_services_id"),
        table_name="current_system_services",
    )
    op.drop_table("current_system_services")
    op.drop_index(
        op.f("ix_current_structural_functional_characteristics_name"),
        table_name="current_structural_functional_characteristics",
    )
    op.drop_index(
        op.f("ix_current_structural_functional_characteristics_id"),
        table_name="current_structural_functional_characteristics",
    )
    op.drop_table("current_structural_functional_characteristics")
    op.drop_index(
        op.f("ix_current_network_interfaces_id"),
        table_name="current_network_interfaces",
    )
    op.drop_table("current_network_interfaces")
    op.drop_index(
        op.f("ix_current_hosts_mac_address"), table_name="current_hosts"
    )
    op.drop_index(
        op.f("ix_current_hosts_ip_address"), table_name="current_hosts"
    )
    op.drop_index(op.f("ix_current_hosts_id"), table_name="current_hosts")
    op.drop_table("current_hosts")
    op.drop_index(
        op.f("ix_current_connections_id"), table_name="current_connections"
    )
    op.drop_table("current_connections")
    op.drop_index(
        op.f("ix_current_arp_table_items_mac_address"),
        table_name="current_arp_table_items",
    )
    op.drop_index(
        op.f("ix_current_arp_table_items_id"),
        table_name="current_arp_table_items",
    )
    op.drop_table("current_arp_table_items")
    op.drop_index(
        op.f("ix_current_applications_name"), table_name="current_applications"
    )
    op.drop_index(
        op.f("ix_current_applications_id"), table_name="current_applications"
    )
    op.drop_table("current_applications")
    op.drop_index(op.f("ix_connections_id"), table_name="connections")
    op.drop_table("connections")
    op.drop_index(
        op.f("ix_arp_table_items_mac_address"), table_name="arp_table_items"
    )
    op.drop_index(op.f("ix_arp_table_items_id"), table_name="arp_table_items")
    op.drop_table("arp_table_items")
    op.drop_index(op.f("ix_applications_name"), table_name="applications")
    op.drop_index(op.f("ix_applications_id"), table_name="applications")
    op.drop_table("applications")
    # ### end Alembic commands ###
